import { Pool, type PoolClient } from "pg";
import { resolve } from "node:path";

export function dataDirectory() {
  return resolve(/* turbopackIgnore: true */ process.env.DATA_DIR || ".data");
}

const state = globalThis as typeof globalThis & { actifyPg?: { url: string; pool: Pool; ready: Promise<void> } };
export async function database() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("Set DATABASE_URL to the PostgreSQL connection URL.");
  if (state.actifyPg && state.actifyPg.url !== url) throw new Error("Close the database pool before changing DATABASE_URL.");
  if (!state.actifyPg) {
    const pool = new Pool({ connectionString: url, max: 8, connectionTimeoutMillis: 5000, statement_timeout: 15000 });
    pool.on("error", () => console.error("PostgreSQL idle connection failed; the next request will reconnect."));
    const ready = (async () => {
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        // Serialize first-start schema creation across Next.js workers.
        await client.query("SELECT pg_advisory_xact_lock(816274, 1)");
        await client.query(`
    CREATE TABLE IF NOT EXISTS content (
      id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('posts','projects')),
      slug TEXT NOT NULL, locked BOOLEAN NOT NULL DEFAULT FALSE, version INTEGER NOT NULL DEFAULT 1,
      data JSONB NOT NULL, published JSONB, deleted_at TEXT, updated_at TEXT NOT NULL,
      UNIQUE(kind, slug)
    );
    CREATE TABLE IF NOT EXISTS feedback (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pain_point TEXT NOT NULL, search_query TEXT NOT NULL DEFAULT '',
      locale TEXT NOT NULL CHECK(locale IN ('en','zh')),
      status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','published','hidden')),
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
    );
    CREATE INDEX IF NOT EXISTS feedback_status_id ON feedback(status, id DESC);
    CREATE TABLE IF NOT EXISTS media (
      id TEXT PRIMARY KEY, filename TEXT NOT NULL UNIQUE, name TEXT NOT NULL, mime TEXT NOT NULL,
      size INTEGER NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, created_at TEXT NOT NULL,
      storage TEXT NOT NULL DEFAULT 'local' CHECK(storage IN ('local','r2')), url TEXT NOT NULL DEFAULT ''
    );
    CREATE TABLE IF NOT EXISTS sessions (hash TEXT PRIMARY KEY, expires BIGINT NOT NULL, credential TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires BIGINT NOT NULL);
        `);
        await client.query("COMMIT");
      } catch (error) { await client.query("ROLLBACK"); throw error; }
      finally { client.release(); }
    })().catch(async (error) => {
      if (state.actifyPg?.pool === pool) delete state.actifyPg;
      await pool.end();
      throw error;
    });
    state.actifyPg = { url, pool, ready };
  }
  const connection = state.actifyPg;
  await connection.ready;
  return connection.pool;
}

export async function transaction<T>(run: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await (await database()).connect();
  try { await client.query("BEGIN"); const value = await run(client); await client.query("COMMIT"); return value; }
  catch (error) { await client.query("ROLLBACK"); throw error; }
  finally { client.release(); }
}

export async function closeDatabase() {
  const connection = state.actifyPg;
  delete state.actifyPg;
  if (connection) { await connection.ready.catch(() => {}); if (!connection.pool.ended) await connection.pool.end(); }
}
