import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";
import { dataDirectory, database, closeDatabase } from "../src/lib/cms-db.ts";
import { createContent, updateContent, getContent, allContent, publishedContent } from "../src/lib/cms-store.ts";
import { emptyTranslation } from "../src/lib/cms-types.ts";
import { importRepository, importFeedback } from "../src/lib/cms-import.ts";
import { setPassword, login, validSession, logout, consumeLimit } from "../src/lib/admin-auth.ts";
import { markdownMetadata } from "../src/lib/markdown.ts";
import { uploadImage } from "../src/lib/media.ts";
import { createBackup, restoreBackup } from "./admin.mjs";

const root = await mkdtemp(join(tmpdir(), "actify-cms-test-"));
process.env.DATA_DIR = join(root, "data");
process.env.MEDIA_STORAGE = "local";
try {
  const files = (await readdir("content/blog")).filter((name) => /\.(md|mdx)$/.test(name));
  assert.equal(importRepository(process.cwd()), files.length + 3);
  const original = JSON.stringify(allContent("posts"));
  assert.equal(importRepository(process.cwd()), 0);
  assert.equal(JSON.stringify(allContent("posts")), original);
  assert.equal(publishedContent("posts").length, 3);
  assert.equal(publishedContent("projects").length, 3);
  let post = createContent("posts");
  const change = (action, extra = {}) => post = updateContent("posts", post.id, { version: post.version, action, ...extra });
  const zh = { ...emptyTranslation(), title: "回归文章", description: "摘要", content: "## 中文标题\n\n正文\n\n## 中文标题\n\n```ts title=\"test.ts\"\nconst n = 1\n```" };
  change("save", { slug: "cms-regression", data: { zh } });
  assert.equal(post.published, null);
  change("publish", { locale: "zh" });
  assert.equal(post.published.zh.title, zh.title);
  assert.equal(post.locked, true);
  const version = post.version;
  change("save", { slug: post.slug, data: { zh: { ...zh, title: "未发布修改" }, en: { ...zh, title: "English" } } });
  assert.equal(post.published.zh.title, zh.title, "Autosave cannot alter published data");
  assert.throws(() => updateContent("posts", post.id, { action: "save", version, slug: post.slug, data: { zh } }), (error) => error.status === 409);
  assert.equal(getContent("posts", post.id).data.zh.title, "未发布修改", "Stale saves never overwrite newer edits");
  assert.throws(() => change("save", { slug: "changed-url", data: post.data }), /不能修改/);
  assert.throws(() => change("save", { slug: "../escape", data: post.data }));
  assert.throws(() => change("save", { slug: post.slug, data: { zh: { ...zh, cover: "javascript:alert(1)" } } }));
  assert.throws(() => change("save", { slug: post.slug, data: { zh: { ...zh, cover: "https://" } } }));
  change("publish", { locale: "en" });
  assert.equal(post.published.zh.title, zh.title);
  change("unpublish", { locale: "zh" });
  assert.ok(!post.published.zh && post.published.en);
  change("trash"); assert.equal(post.published, null);
  assert.throws(() => change("publish", { locale: "en" }), /恢复/);
  change("restore"); assert.equal(post.published, null, "Restore keeps content private");
  assert.equal(post.locked, true, "Withdrawn URLs remain locked");
  change("publish", { locale: "zh" });
  assert.equal(post.published.zh.title, "未发布修改");
  const meta = markdownMetadata(zh.content);
  assert.deepEqual(meta.toc.map((item) => item.id), ["section-中文标题", "section-中文标题-2"]);
  assert.equal(markdownMetadata("中".repeat(601)).readingMinutes, 3);
  assert.throws(() => updateContent("posts", createContent("posts").id, { version: 1, action: "publish", locale: "zh" }), /标题/);
  let project = createContent("projects");
  project = updateContent("projects", project.id, { version: project.version, action: "save", slug: "project-check", data: { ...project.data, name: "Test", description: { zh: "中文简介", en: "English" }, featured: true } });
  project = updateContent("projects", project.id, { version: project.version, action: "publish" });
  assert.equal(project.published.featured, true);
  project = updateContent("projects", project.id, { version: project.version, action: "save", slug: project.slug, data: { ...project.data, name: "New" } });
  assert.equal(project.published.name, "Test");
  const importedFeedback = [{ id: 1, pain_point: "反馈导入测试", search_query: "私有关键词", locale: "zh", status: "pending", created_at: "2026-09-21 00:00:00" }];
  assert.equal(importFeedback([{ results: importedFeedback }]), 1);
  assert.equal(importFeedback(importedFeedback), 0);
  await setPassword("cms-test-password-2026");
  await assert.rejects(login("wrong-password", "test"), (error) => error.status === 401);
  const token = await login("cms-test-password-2026", "test"); assert.ok(validSession(token)); logout(token); assert.ok(!validSession(token));
  const rotated = await login("cms-test-password-2026", "test"); await setPassword("new-test-password-2026"); assert.ok(!validSession(rotated));
  const expired = await login("new-test-password-2026", "test"); database().exec("UPDATE sessions SET expires=0"); assert.ok(!validSession(expired));
  for (let i = 0; i < 3; i++) consumeLimit("test-limit", 3, 60);
  assert.throws(() => consumeLimit("test-limit", 3, 60), (error) => error.status === 429);
  for (const [format, mime] of [["png", "image/png"], ["jpeg", "image/jpeg"], ["webp", "image/webp"], ["gif", "image/gif"]]) {
    const buffer = await sharp({ create: { width: 20, height: 10, channels: 3, background: "white" } }).toFormat(format).toBuffer();
    const image = await uploadImage(buffer, `test.${format}`, mime);
    assert.equal(image.width, 20); assert.equal(image.height, 10);
    assert.ok((await readFile(join(dataDirectory(), "uploads", image.filename))).length > 0);
    await assert.rejects(uploadImage(buffer, "spoof.png", "text/html"));
  }
  await assert.rejects(uploadImage(Buffer.from('<svg onload="alert(1)"/>'), "fake.png", "image/png"));
  await assert.rejects(uploadImage(Buffer.from([137, 80, 78, 71]), "truncated.png", "image/png"));
  const snapshot = JSON.stringify(allContent("posts"));
  const backupPath = await createBackup(join(root, "backup"));
  await assert.rejects(restoreBackup(backupPath, process.env.DATA_DIR), /empty DATA_DIR/);
  await restoreBackup(backupPath, join(root, "restored"));
  closeDatabase(); process.env.DATA_DIR = join(root, "restored");
  assert.equal(JSON.stringify(allContent("posts")), snapshot);
  assert.equal(database().prepare("SELECT count(*) AS n FROM media").get().n, 4);
  assert.equal(database().prepare("SELECT count(*) AS n FROM sessions").get().n, 0);
  assert.equal(importRepository(process.cwd()), 0, "Re-import after restore is harmless");
  await writeFile(join(backupPath, "uploads", (await readdir(join(backupPath, "uploads")))[0]), "corrupt");
  await assert.rejects(restoreBackup(backupPath, join(root, "bad-restore")), /corrupted/);
  console.log("CMS checks passed: imports, draft isolation, publication, translations, conflicts, URL locking, projects, auth, throttling, decoded uploads, backup and restore.");
} finally { closeDatabase(); }
