import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";
import { dataDirectory, database, closeDatabase } from "../src/lib/cms-db.ts";
import { createContent, updateContent, getContent, allContent, publishedContent } from "../src/lib/cms-store.ts";
import { emptyTranslation } from "../src/lib/cms-types.ts";
import { login, validSession, logout, consumeLimit, clientIp } from "../src/lib/admin-auth.ts";
import { markdownMetadata } from "../src/lib/markdown.ts";
import { uploadImage } from "../src/lib/media.ts";
import { createBackup, restoreBackup } from "./admin.mjs";
import { testDatabase } from "./postgres-test.mjs";

const testDb = await testDatabase();
const root = await mkdtemp(join(tmpdir(), "actify-cms-test-"));
process.env.DATA_DIR = join(root, "data");
process.env.MEDIA_STORAGE = "local";
try {
  assert.deepEqual(await publishedContent("posts"), []);
  assert.deepEqual(await publishedContent("projects"), []);
  let post = await createContent("posts");
  const change = async (action, extra = {}) => post = await updateContent("posts", post.id, { version: post.version, action, ...extra });
  const zh = { ...emptyTranslation(), title: "回归文章", description: "摘要", content: "## 中文标题\n\n正文\n\n## 中文标题\n\n```ts title=\"test.ts\"\nconst n = 1\n```" };
  await change("save", { slug: "cms-regression", data: { zh } });
  assert.equal(post.published, null);
  await change("publish", { locale: "zh" });
  assert.equal(post.published.zh.title, zh.title);
  assert.equal(post.locked, true);
  const version = post.version;
  await change("save", { slug: post.slug, data: { zh: { ...zh, title: "未发布修改" }, en: { ...zh, title: "English" } } });
  assert.equal(post.published.zh.title, zh.title, "Autosave cannot alter published data");
  await assert.rejects(() => updateContent("posts", post.id, { action: "save", version, slug: post.slug, data: { zh } }), (error) => error.status === 409);
  assert.equal((await getContent("posts", post.id)).data.zh.title, "未发布修改", "Stale saves never overwrite newer edits");
  await assert.rejects(() => change("save", { slug: "changed-url", data: post.data }), /不能修改/);
  await assert.rejects(() => change("save", { slug: "../escape", data: post.data }));
  await assert.rejects(() => change("save", { slug: post.slug, data: { zh: { ...zh, cover: "javascript:alert(1)" } } }));
  await assert.rejects(() => change("save", { slug: post.slug, data: { zh: { ...zh, cover: "https://" } } }));
  await change("publish", { locale: "en" });
  assert.equal(post.published.zh.title, zh.title);
  await change("unpublish", { locale: "zh" });
  assert.ok(!post.published.zh && post.published.en);
  await change("trash"); assert.equal(post.published, null);
  await assert.rejects(() => change("publish", { locale: "en" }), /恢复/);
  await change("restore"); assert.equal(post.published, null, "Restore keeps content private");
  assert.equal(post.locked, true, "Withdrawn URLs remain locked");
  await change("publish", { locale: "zh" });
  assert.equal(post.published.zh.title, "未发布修改");
  const meta = markdownMetadata(zh.content);
  assert.deepEqual(meta.toc.map((item) => item.id), ["section-中文标题", "section-中文标题-2"]);
  assert.equal(markdownMetadata("中".repeat(601)).readingMinutes, 3);
  await assert.rejects(async () => updateContent("posts", (await createContent("posts")).id, { version: 1, action: "publish", locale: "zh" }), /标题/);
  let project = await createContent("projects");
  project = await updateContent("projects", project.id, { version: project.version, action: "save", slug: "project-check", data: { ...project.data, name: "Test", description: { zh: "中文简介", en: "English" }, featured: true } });
  project = await updateContent("projects", project.id, { version: project.version, action: "publish" });
  assert.equal(project.published.featured, true);
  project = await updateContent("projects", project.id, { version: project.version, action: "save", slug: project.slug, data: { ...project.data, name: "New" } });
  assert.equal(project.published.name, "Test");
  process.env.ADMIN_USERNAME = "cms-admin";
  process.env.ADMIN_PASSWORD = "";
  await assert.rejects(login("cms-admin", "anything"), (error) => error.status === 503);
  process.env.ADMIN_PASSWORD = "short";
  await assert.rejects(login("cms-admin", "short"), (error) => error.status === 503);
  process.env.ADMIN_PASSWORD = "cms-test-password-2026";
  const passwordError = await login("cms-admin", "wrong-password").catch((error) => error);
  const usernameError = await login("wrong-user", process.env.ADMIN_PASSWORD).catch((error) => error);
  assert.equal(passwordError.status, 401); assert.equal(usernameError.message, passwordError.message);
  const token = await login("cms-admin", process.env.ADMIN_PASSWORD); assert.ok(await validSession(token)); await logout(token); assert.ok(!await validSession(token));
  const rotated = await login("cms-admin", process.env.ADMIN_PASSWORD);
  process.env.ADMIN_PASSWORD = "new-test-password-2026"; assert.ok(!await validSession(rotated));
  const renamed = await login("cms-admin", process.env.ADMIN_PASSWORD);
  process.env.ADMIN_USERNAME = "renamed-admin"; assert.ok(!await validSession(renamed));
  const expired = await login(process.env.ADMIN_USERNAME, process.env.ADMIN_PASSWORD);
  process.env.ADMIN_USERNAME = ""; assert.ok(!await validSession(expired));
  await assert.rejects(login("", process.env.ADMIN_PASSWORD), (error) => error.status === 503);
  process.env.ADMIN_USERNAME = "renamed-admin";
  await (await database()).query("UPDATE sessions SET expires=0"); assert.ok(!await validSession(expired));
  const proxyRequest = new Request("https://example.test", { headers: { "X-Real-IP": "203.0.113.1", "X-Forwarded-For": "203.0.113.2" } });
  process.env.TRUST_PROXY = "0"; assert.equal(clientIp(proxyRequest), "direct");
  process.env.TRUST_PROXY = "1"; assert.equal(clientIp(proxyRequest), "203.0.113.1");
  assert.equal(clientIp(new Request("https://example.test", { headers: { "X-Real-IP": "invalid" } })), "direct");
  const limits = await Promise.allSettled(Array.from({ length: 10 }, () => consumeLimit("test-limit", 3, 60)));
  assert.equal(limits.filter((result) => result.status === "fulfilled").length, 3, "Concurrent limits must be atomic");
  assert.ok(limits.filter((result) => result.status === "rejected").every((result) => result.reason.status === 429));
  await (await database()).query("UPDATE rate_limits SET expires=0 WHERE key='test-limit'");
  await consumeLimit("test-limit", 3, 60);
  const simultaneous = await Promise.allSettled(["A", "B"].map((title) => updateContent("posts", post.id, { version: post.version, action: "save", slug: post.slug, data: { zh: { ...zh, title } } })));
  assert.equal(simultaneous.filter((result) => result.status === "fulfilled").length, 1);
  assert.equal(simultaneous.find((result) => result.status === "rejected").reason.status, 409);
  const winner = simultaneous.find((result) => result.status === "fulfilled").value;
  assert.equal((await getContent("posts", post.id)).data.zh.title, winner.data.zh.title);
  const duplicates = await Promise.all([createContent("posts"), createContent("posts")]);
  const collisions = await Promise.allSettled(duplicates.map((entry) => updateContent("posts", entry.id, { version: 1, action: "save", slug: "same-slug", data: { zh } })));
  assert.equal(collisions.filter((result) => result.status === "fulfilled").length, 1);
  assert.equal(collisions.find((result) => result.status === "rejected").reason.status, 409);
  for (const [format, mime] of [["png", "image/png"], ["jpeg", "image/jpeg"], ["webp", "image/webp"], ["gif", "image/gif"]]) {
    const buffer = await sharp({ create: { width: 20, height: 10, channels: 3, background: "white" } }).toFormat(format).toBuffer();
    const image = await uploadImage(buffer, `test.${format}`, mime);
    assert.equal(image.width, 20); assert.equal(image.height, 10);
    assert.ok((await readFile(join(dataDirectory(), "uploads", image.filename))).length > 0);
    await assert.rejects(uploadImage(buffer, "spoof.png", "text/html"));
  }
  await assert.rejects(uploadImage(Buffer.from('<svg onload="alert(1)"/>'), "fake.png", "image/png"));
  await assert.rejects(uploadImage(Buffer.from([137, 80, 78, 71]), "truncated.png", "image/png"));
  const snapshot = JSON.stringify(await allContent("posts"));
  const backupPath = await createBackup(join(root, "backup"));
  await assert.rejects(restoreBackup(backupPath, process.env.DATA_DIR), /empty DATA_DIR/);
  await assert.rejects(restoreBackup(backupPath, join(root, "existing-db")), /empty PostgreSQL/);
  await testDb.next();
  await restoreBackup(backupPath, join(root, "restored"));
  await closeDatabase(); process.env.DATA_DIR = join(root, "restored");
  assert.equal(JSON.stringify(await allContent("posts")), snapshot);
  assert.equal((await (await database()).query("SELECT count(*)::int AS n FROM media")).rows[0].n, 4);
  assert.equal((await (await database()).query("SELECT count(*)::int AS n FROM sessions")).rows[0].n, 0);
  await writeFile(join(backupPath, "uploads", (await readdir(join(backupPath, "uploads")))[0]), "corrupt");
  await assert.rejects(restoreBackup(backupPath, join(root, "bad-restore")), /corrupted/);
  console.log("CMS checks passed: draft isolation, publication, translations, conflicts, URL locking, projects, auth, throttling, decoded uploads, backup and restore.");
} finally { await testDb.cleanup(); }
